### ISSUE TITLE
[TUI] Link cropped when wrapped to multiple lines

### ISSUE THREAD

**Issue by UncleReaton** [bacardi55/gtl#22]
When the terminal width is small then the text is wrapped to more lines but if a link is wrapped only the first line is considered a link.
e.g. : 
`=>https://github.com/bacardi55/gtl/releases/tag/v0.4.5` when wrapped will look like this for instance : 
```
https://github.com/bacar
di55/gtl/releases/tag/v0.4.5
```
Only the first line is a link, so this link brings us to @\bacar profile.

I don't know if I'm very clear on this issue, sorry if it's the case :[]

**Comment by bacardi55** [comment]
If I understand correctly, it is like #23 and due to how terminal works…
I have the same issue in neomutt or weechat when a link in on multiple line within a TUI (curses or not) app…
