### ISSUE TITLE
[TUI] Text selection

### ISSUE THREAD

**Issue by UncleReaton** [bacardi55/gtl#23]
II know this is very specific so no problem if it's not a priority or even not in your plan at all. In my terminals (ST & urxvt) I'm unable to click on links, so it could be cool if we could select text so that we can copy links (or even any other text).

Something to note: I'm able to click on tinylogs names in the subscription panel.

**Comment by bacardi55** [comment]
If I understand correctly, this is more a terminal related issue.
Eg: I can click on http(s) links but not gemini/gopher links. But that's not gtl that makes links clickable.
So to copy a link at least, this is also based on your terminal emulator, usually, shift + click + select text. Then right click and copy. that's just a usual default, it might not be true for ST that I never used.

The fact that subscriptions can be clicked is indeed something managed within gtl on the other hand.

PS: I also need to start looking at enabling gemini links in my term^^

**Comment by UncleReaton** [comment]
Dang, I didn't thought about using shift lol. Shame on me.
