### ISSUE TITLE
displays only the named Tinylog (except the last one which is always displayed)

### ISSUE THREAD

**Issue by UncleReaton** [bacardi55/gtl#3]
e.g. When my .config/gtl/subs looks like this:
```
<url1> name1
<url2>
<url3> name3
<url4>
```
It's gonna display tinylog just for `<url1>`,`<url3>` and `<url4>`.

If I only name `<url3>` it's gonna display `<url3>` and `<url4>`

**Comment by bacardi55** [comment]
That's a weird one I've never seen (even though i do have a mix too), I'll test it today with the provided format.
Thanks a lot for testing and reporting!

Did you try based on the latest commit? I've worked a bit on that area yesterday …

**Comment by UncleReaton** [comment]
Yeah I tried with the last commit

**Comment by bacardi55** [comment]
Don't tell my boss, but it should be fixed in latest commit :)
Thanks a lot for testing and reporting issues!

**Comment by UncleReaton** [comment]
Haha I won't I promise :D
Indeed, the issue is fixed 🎉 

> Thanks a lot for testing and reporting issues!

It's a pleasure to help! :)
