### ISSUE TITLE
panic: runtime error: slice bounds out of range [3:2]

### ISSUE THREAD

**Issue by szczja** [bacardi55/gtl#30]
Program crashed while it has been running and doesn’t work after it. 

$ gtl
panic: runtime error: slice bounds out of range [3:2]

goroutine 1 [running]:
git.bacardi55.io/bacardi55/gtl/core.parseTinyLogItemForDate(0xc00027a1df, 0x2, 0x756f58, 0x1, 0x0, 0x2, 0xc00006bd70)
        /home/bacardi55/workspace/perso/gtl/core/parser.go:205 +0x23c
git.bacardi55.io/bacardi55/gtl/core.parseTinyLogItem(0xc00027a1df, 0x89, 0xc0002f85f1, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bacardi55/workspace/perso/gtl/core/parser.go:191 +0x125
git.bacardi55.io/bacardi55/gtl/core.parseTinyLogContent(0xc0000257ec, 0x8, 0xc00027a000, 0x1fcf, 0x1, 0x88, 0x13e, 0x300, 0x88, 0x100, ...)
        /home/bacardi55/workspace/perso/gtl/core/parser.go:133 +0x45f
git.bacardi55.io/bacardi55/gtl/core.refreshStream(0xc0000fad20, 0xc000184000, 0x0, 0x0, 0x0, 0x0)
        /home/bacardi55/workspace/perso/gtl/core/feeds.go:42 +0x5fc
git.bacardi55.io/bacardi55/gtl/core.(*TlData).RefreshFeeds(...)
        /home/bacardi55/workspace/perso/gtl/core/structs.go:22
git.bacardi55.io/bacardi55/gtl/ui.displayStreamTui(0x938cb0, 0x7, 0x0)
        /home/bacardi55/workspace/perso/gtl/ui/tui.go:32 +0x47
git.bacardi55.io/bacardi55/gtl/ui.(*TlUI).Run(0xc00017fed8, 0x938cb0, 0x0, 0x0, 0x0)
        /home/bacardi55/workspace/perso/gtl/ui/utils.go:19 +0xb1
main.main()
        /home/bacardi55/workspace/perso/gtl/gtl.go:87 +0x54e

**Comment by bacardi55** [comment]
This has been fixed yesterday night and is due to a malformed entry (in my case on deerbard tinylog).
I published in the middle of the night a v0.5.2 that fixes it.
