### ISSUE TITLE
Show the tinylog entry being replied to

### ISSUE THREAD

**Issue by Perelandra0x309** [bacardi55/gtl#36]
If a reply is found in a tinylog entry that refers to another tinylog that is known (in the subs list) then clicking on the reply line could either:
* open that tinylog in the window and scroll to the referenced entry (and going back should return you to the last cursor location of the previous tinylog)
* open a popup window which displays only the referenced entry, not the entire tinylog (and clicking outside the window hides it to return to the previous tinylog)

**Comment by bacardi55** [comment]
Thanks for the idea, I like it!
This is blocked until the next release though as I'm reworking the timeline UI, but the work done might help implement this later down the road!
So I'll look again at this after the v0.6.0 release.

**Comment by bacardi55** [comment]
Implemented in a86d729b6c2868c0b5a9b751818e851efd50d6f6
Will be available in v0.6.0
