### ISSUE TITLE
Entries with ## within a preformated text are failing

### ISSUE THREAD

**Issue by bacardi55** [bacardi55/gtl#43]
Bug reported by samhunter:

- my post was cut at line 4, most probably because the # in line 5 was
  interpreted as a header _although it was within a preformatted area_

- consistently, the rest of the page, including all logs following mine,
  was formatted as "preformatted text"

        V--- actual column 1, the number added for convenience
     1  ## Tue 24 Aug 2021 12:42:25 PM CEST
     2  ### Context
     3  Not so important, are you?
     4  ```
     5  #
     6  ##         you are
     7  ####        here
     8  ####         |
     9  #####        v                  ,
    10  #####--.--o--o---°------(()---(/)---O-----O-----------------------------------
    11  #####                         '
    12  ####
    13  ####
    14  ##
    15  #
    16  ```

I tweaked it slightly, prefixing every 'preformatted' line with a space,
and it seems to help...

     1  ## Tue 24 Aug 2021 12:42:25 PM CEST
     2  ### Context
     3  Not so important, are you?
     4  ```
     5   #
     6   ##         you are
     7   ####        here
     8   ####         |
     9   #####        v                  ,
    10   #####--.--o--o---°------(()---(/)---O-----O-----------------------------------
    11   #####                         '
    12   ####
    13   ####
    14   ##
    15   #
    16  ```

**Comment by samhunter** [comment]
I think you have the wrong person, I didn't report this bug.

**Comment by bacardi55** [comment]
> I think you have the wrong person, I didn't report this bug.

sorry, someone else with a samhunter nick send this to me via email and I just used @ before so it pings you, apologies

**Comment by bacardi55** [comment]
Will require a significant rework on the parser.
Maybe for a 2.x version with a reworked parser and better UI?
