### ISSUE TITLE
Allow custom theme in configuration

### ISSUE THREAD

**Issue by ghost** [bacardi55/gtl#44]
Is it possible to add light theme for TUI mode?

**Comment by bacardi55** [comment]
Hi @tolstoevsky, thanks for the ticket (and using gtl :)).
Normally gtl leverage the terminal theme so if the term theme is light it should stay light.
But I admit I've never tested it like that as all my system is configured with a darker theme (dracula).

Could you please share a screenshot of a clean term (that should be light theme) and gtl running in it (not being in a light theme).

I can work on a theme approach, but I do have very bad UX/UI taste :D

**Comment by ghost** [comment]
Thanks for response!
Screenshots:

![20220202_14h47m13s_grim](https://user-images.githubusercontent.com/36292035/152148514-c826914c-149e-43bc-b0b1-73113d11730c.png)
![20220202_14h47m37s_grim](https://user-images.githubusercontent.com/36292035/152148590-269f3bef-075a-46b3-ab4f-283141572f79.png)

**Comment by bacardi55** [comment]
Interesting, thanks for the screenshot!
I've never dev a TUI with configurable theme before but see if I can make it work :)

As a side note, I can see in your screenshot that GTL feeds seems down. Is that often the case?

**Comment by ghost** [comment]
> I can see in your screenshot that GTL feeds seems down. Is that often the case?

Not every day, but happens time to time. Didn't gather stats :)

**Comment by bacardi55** [comment]
Has been implemented in 7b1fd4a3100b79140528bd76d12402efdb7e18dc
The documentation is [here](https://github.com/bacardi55/gtl/blob/main/docs/mode-tui-theming.md).

It's not in a stable release yet (will be in v0.7.0), but would love some tests :)

**Comment by ghost** [comment]
![2022-02-16-161906_1392x645_scrot](https://user-images.githubusercontent.com/36292035/154272914-33f2e158-17f4-4fc7-bc8d-92c6f965f1a9.png)

It works fine, thanks a lot!

**Comment by bacardi55** [comment]
Awesome! I'm closing this ticket, but feel free to open new one if anything doesn't work with custom theme (or for any other ideas :))
