### ISSUE TITLE
dies on blank line in 'subs' file

### ISSUE THREAD

**Issue by stacksmith** [bacardi55/gtl#45]
If there is a blank line in the `.config/gtl/subs` file, gtl dies silently immediately upon startup.

In fact, even having a CR at the end causes this, as emacs seems to add a CR silently,  So a perfectly-good 1-line subs file crashes.  So I have to delete everything leaving the last line un-CR'ed.  Weird.

I figured `add` option from the command line would do the right thing.  But no, it added the provided uri/name to the same line, and again, gtl crashed.

**Comment by bacardi55** [comment]
Thanks for the report! I'll work on it :)
