### ISSUE TITLE
Error with the access path to tcell

### ISSUE THREAD

**Issue by UncleReaton** [bacardi55/gtl#7]
In the pre-release 0.4.1, it's impossible to make the dependencies due to a bad path.
It's returning this : 
`go get: malformed module path "github.com/gdamore/tcell/v2 v2.3`

**A quick work-around is to change in the Makefile `github.com/gdamore/tcell/v2 v2.3` to `github.com/gdamore/tcell`**.
After it's done, everything works fine.

**Comment by bacardi55** [comment]
Thanks again for the tests!
I really should test more the Makefile dependencies (I could automate that with a docker container to test on a clean install).

Fixed in main branch, I'll release v0.4.2 tonight to fix this.

**Comment by UncleReaton** [comment]
Fixed in ade9fa25fffa123faec0086cc568f078efee4223 . 🎉
